### ISSUE TITLE
tool/bed target temperature fields too narrow

### ISSUE THREAD

**Issue by ronaldcleanfield** [jneilliii/OctoPrint-WideScreen#20]
Hi, thanks for the widescreen plugin.

I have a little issue that I cannot read the target tool/bed temperatures because the entry fields are too narrow. I am not sure if the picture I added is visible but I have the menus left and right. The "target" values are the entry boxes below the graph. There is plenty of horizontal space to have wider boxes.
I would appreciate if you can provide me with advise how to fix this (or with an update).
Thanks a lot. 

![widescreen](https://user-images.githubusercontent.com/58135360/110841235-f1084d80-82a5-11eb-82d9-2afb480a3c81.png)

**Comment by jneilliii** [comment]
I think this may be an adjustment you need to do in Themeify's advanced customization settings because it's doesn't do that on a standard non-themed OctoPrint.

![image](https://user-images.githubusercontent.com/5249455/110868584-dc708900-8296-11eb-86a0-685ebde25259.png)

The specific things that need to be adjusted I think are below.

| Selector                                                                      | CSS-Rule | Value |
|-------------------------------------------------------------------------------|----------|-------|
| #temperature-table td.temperature_target div.input-prepend.input-append input | width    | 30px  |

**Comment by ronaldcleanfield** [comment]
Hi, thanks for the tip. 
Your suggestion does not 100% work but for sure your conclusion is spot on that this issue is relating themeify.

At first when making this update both fields are okay (@60px) but after a screen refresh the tool target is narrow again but the bed target is still wide!? I see that themeify clamps the selector to "#temperature-table td.temperature_target div.input-prepend.input-ap" but it even behaves exactly the same when I put just "input" as the selector.

Anyway I will bring it up at the themeify page that it does not fully work with your widescreen plugin. 
Cheers

**Comment by jneilliii** [comment]
My best guess is that it works when making the change because of the way Themeify is setting those dynamically with jQuery and the individual rows themselves are also getting created dynamically via knockout, so it's going to be difficult to get a full solution. I'll see if I can do something from my css side to counter this in any way.

**Comment by jneilliii** [comment]
It actually does look like this might be specific to a certain theme. The discoranged and discorded themes don't seem to do this, so I do think this might be an issue on the Themeify side that might be better suited to fix over there.
